#!/usr/bin/perl -l

use strict;
use warnings;

use Acme::LOLCAT;

# This is a simple command line based translater.
#
# Have lolcli in your path, and feed it some text:
#
# $ lolcli this is some test text, isn't it neat?
#
# Output:
#
# THIZ AR TEH SUM TEST TET, ISNT IT NEAT?
my @stdin = <STDIN>;
#print translate( join ' ', @ARGV );
print translate( join ' ', @stdin);

