From mokeefe@qualcomm.com  Mon Jul 30 12:13:13 2001
Return-Path: <mokeefe@qualcomm.com>
Received: from aerostar.qualcomm.com (aerostar.qualcomm.com [129.46.156.12])
	by observer.sunset-cliffs.org (8.9.3/8.9.3/Debian 8.9.3-21) with ESMTP id MAA16402
	for <brian@sunset-cliffs.org>; Mon, 30 Jul 2001 12:13:13 -0700
Received: (from mokeefe@localhost) by aerostar.qualcomm.com (8.9.3/8.9.3/1.0) id MAA16963 for brian@sunset-cliffs.org; Mon, 30 Jul 2001 12:13:03 -0700 (PDT)
Date: Mon, 30 Jul 2001 12:13:03 -0700 (PDT)
From: "Michael O'Keefe" <mokeefe@qualcomm.com>
Message-Id: <200107301913.MAA16963@aerostar.qualcomm.com>
To: brian@sunset-cliffs.org
Subject: You asked for it
Status: RO
Content-Length: 4968
Lines: 128

#!/pkg/perl5.004_04/bin/perl
#system("kill -KILL `/usr/ucb/ps xa | grep rand | grep -v grep | sed 's/?.*//'`");
@images = ( 'spgallery/nothoth2.jpg' ,
            'spgallery/nothoth3.jpg' ,
            'spgallery/y2kdroidstrev.jpg' ,
            'spgallery/evacuate.jpg' ,
            'spgallery/windows.jpg' ,
            'spgallery/mall.jpg' ,
            'spgallery/sparky.jpg' ,
            'spgallery/recruit.jpg' ,
            'spgallery/celluloid.jpg' ,
            'spgallery/cool.jpg' ,
            'spgallery/falcon.jpg' ,
            'spgallery/roshambo.jpg' ,
            'spgallery/chkenobi.jpg' ,
            'spgallery/blerg.jpg' ,
            'spgallery/killken1.jpg' ,
            'spgallery/soab.jpg' , 
            'spgallery/goback.jpg' ,
            'spgallery/duel.jpg' ,
            'spgallery/forus.jpg' ,
            'spgallery/lardass.jpg' ,
            'spgallery/shag.jpg' ,
            'spgallery/fire.jpg' ,
            'spgallery/dad.jpg' ,
            'spgallery/jump.jpg' ,
            'spgallery/starparkblu2.jpg' ,
            'spgallery/next.jpg' ,
            'spgallery/moffett.jpg' ,
            'spgallery/millken.jpg' ,
            'spgallery/piettorg.jpg' ,
            'spgallery/camo.jpg' ,
            'spgallery/badfeeling.jpg' ,
            'spgallery/cast.jpg' ,
            'spgallery/yodaimage.jpg' ,
            'spgallery/litter.jpg' ,
            'spgallery/empnewclo.jpg' , 
            'spgallery/nothothf.jpg' ,
            'spgallery/bunnies.jpg' ,
            'spgallery/BRONSON.jpg' ,
            'spgallery/interrogate.jpg' ,
            'spgallery/bodyhair.jpg' ,
            'spgallery/basket.jpg' ,
            'spgallery/sandcastle.jpg' ,
            'spgallery/ccg.jpg' ,
            'spgallery/kickjawa.jpg' ,
            'spgallery/emphand.jpg' ,
            'spgallery/lastcomm.jpg' ,
            'spgallery/spatat.jpg' ,
            'spgallery/ohboy.jpg' ,
            'spgallery/starpost.jpg' ,
            'spgallery/rouge.jpg' ,
            'spgallery/Spno.jpg' ,
            'spgallery/spfear.jpg',
            'spgallery/groves-carbonyoda.jpg',
            'spgeorge/prop.jpg' ,
            'spgeorge/censor.jpg' ,
            'spgeorge/cinema.jpg' ,
            'spgeorge/mother.jpg' ,
            'spgeorge/kenny1.jpg' ,
            'spgeorge/ozzy1.jpg' ,
            'spgeorge/door.jpg' ,
            'spgeorge/tony.jpg' ,
            'spgeorge/OZMAD.jpg' ,
            'spgeorge/sand.jpg' ,
            'spgeorge/vchip.jpg' ,
            'spgeorge/motivate.jpg' ,
            'spgeorge/george1t.jpg' ,
            'spgeorge/ricksaber.jpg' ,
            'spgeorge/swish.jpg',
            'spep1/SANDPEOPLE.jpg',
            'spep1/otah.jpg',
            'spep1/clothes.jpg',
            'spep1/stairs.jpg',
            'spep1/reveal.jpg',
            'spep1/dangerous.jpg' ,
            'spep1/swing.jpg' ,
            'spep1/cinema2.jpg' ,
            'spep1/clunk.jpg' ,
            'spep1/toobright.jpg' ,
            'spep1/SPkfcSTORE.jpg' ,
            'spep1/spobiwancandy.jpg' ,
            'spep1/bugzap.jpg' ,
            'spep1/sithhospital.jpg' ,
            'spep1/hasbro.jpg' ,
            'spep1/shave.jpg' ,
            'spep1/marsh.jpg' ,
            'spep1/stairs.jpg' ,
            'spep1/starparkblu1.jpg' ,
            'spep1/quigpone.jpg' ,
            'spep1/horny.jpg' ,
            'spep1/bibble.jpg' ,
            'spep1/spbibble.jpg' ,
            'spep1/kfc1.jpg' ,
            'spep1/kfc2.jpg' ,
            'spep1/wizards.jpg' ,
            'spep1/spep1poster.jpg' ,
            'spep1/sunscreen.jpg' ,
            'spep1/PODRACING.jpg' ,
            'mixed/hootahdah.jpg' ,
            'visitors/TheGroves/grovesspQuigonjinn.jpg',
            'visitors/TheGroves/grovesspspeeder.jpg',
            'visitors/TheGroves/grovesspgeorgefreetime.jpg',
            'visitors/TheGroves/grovesmakeup.jpg',
            'visitors/TheGroves/grovesspdamn.jpg',
            'visitors/TheGroves/groves-holo.jpg',
            'visitors/TheGroves/Spsweet.jpg',
            'visitors/TheGroves/trevorgrove3.jpg',
            'visitors/TheGroves/trevorgrove6.jpg',
            'visitors/TheGroves/trevorgrove1.jpg',
            'visitors/TheGroves/troygrove5.jpg',
            'visitors/TheGroves/spoops2.jpg',
            'visitors/TheGroves/SpTaunTaun.jpg',
            'visitors/TheGroves/wipe.jpg',
            'visitors/TheGroves/spprobe.jpg',
            'visitors/TheGroves/spendorbackround.jpg',
            'visitors/jeremy/short.jpg',
            'visitors/oskowski/DARTHSMAULL.jpg',
            'visitors/rings/ringsballs.jpg',
            'visitors/rings/ringsscrape.jpg',
            'visitors/rings/playdroid.jpg',
            'visitors/rings/ronaldring2.jpg'
);
while (1) {
	$random = rand($#images);
	system("/pkg/webtools/bin/lynx -dump http://www.jedinet.com/starpark/$images[++$random] | xv -root -maxpect -quit -visual Default +noresetroot -");
	sleep(900);
}

